# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: api lint, format, test
        run: |
          yarn
          yarn workspace api run lint:js
          yarn workspace api run lint:format:check
          yarn workspace api run test:ci:all
      - name: web lint, format, test
        run: |
          yarn
          yarn workspace web run lint:js
          yarn workspace web run lint:format:check
          yarn workspace web run test:ci:all
