name: delete branch on close pr
on:
  pull_request:
    types: [closed]
    branches-ignore:
      - main
      - dev
      - auth-api-dev
      - data-api-dev

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
